# Author:  mozman
# License: MIT-License

RUNTESTS = -m unittest discover -s tests

PYTHON2 = python
PYTHON3 = python3
PYPY = pypy

test2:
	$(PYTHON2) $(RUNTESTS)

test3:
	$(PYTHON3) $(RUNTESTS)
	
testpypy:
	$(PYPY) $(RUNTESTS)

testall: test2 test3 testpypy

packages:
	python setup.py sdist --formats=zip,gztar
	python setup.py bdist_wheel


pypi:
	python setup.py sdist --formats=zip,gztar upload
	python setup.py bdist_wheel upload
